PRODUCT_LINES = [
    "assembly",
    "friction",
    "injection",
    "seals",
    "brushes",
    "chokes",
]

PLANTS = [
    "Poitiers",
    "Amiens",
    "Mexico",
    "Tianjin",
    "Frankfurt",
    "Tunisia",
    "Kunshan",
    "Chennai",
]

CUSTOMERS = [
    "AAM",
    "Aisin",
    "Bosch",
    "BorgWarner",
    "Continental",
    "Denso",
    "Delphi",
    "Eaton",
    "Federal-Mogul",
    "Faurecia",
    "GKN",
    "Hitachi",
    "Hyundai Mobis",
    "Johnson Controls",
    "Lear Corporation",
    "Magna",
    "Mahle",
    "Marelli",
    "Mitsuba",
    "Mitsubishi Electric",
    "NGK",
    "NSK",
    "NTN",
    "Panasonic",
    "Plastic Omnium",
    "Renault",
    "Robert Bosch",
    "Schaeffler",
    "Tenneco",
    "Valeo",
    "Vitesco Technologies",
    "ZF Friedrichshafen",
]

# Status workflow
REQUEST_STATUS_STAGES = {
    "DRAFT": 0,
    "SUBMITTED": 1,
    "UNDER_REVIEW_PL": 2,
    "ESCALATED_TO_VP": 3,
    "APPROVED_BY_PL": 4,
    "APPROVED_BY_VP": 4,
    "REJECTED_BY_PL": 5,
    "REJECTED_BY_VP": 5,
    "BACK_TO_COMMERCIAL": 2,
    "CLOSED": 6,
}
